-- Initial schema for OrbitFi

CREATE TABLE IF NOT EXISTS user_settings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	key TEXT UNIQUE NOT NULL,
	value TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	type TEXT,
	balance REAL DEFAULT 0,
	created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	parent_id INTEGER,
	created_at TEXT DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(parent_id) REFERENCES categories(id)
);
